### ISSUE TITLE
Bug in v1.7.5 - appWaitActivity

### ISSUE THREAD

**Issue by email2vimalraj** [appium/appium-adb#138]
If the appWaitActivity capability is comma-sepearted, like this:
`appWaitActivity: com.example.demo.activities.Activity1,com.example.demo.activities.Activity2`, then the `launchApp` fails.

The reason is, in `adb.js`, we are doing this in the method `waitForActivityOrNot`:
1. Parsing the relative name of the activity given
2. Then we are splitting by comma on the relative name (Refer: https://github.com/appium/appium-adb/blob/v1.7.5/lib/adb.js#L1285)

However, it should be:
1. Split by comma first
2. then we should parse the relative name of the activity.

Since `appium v1.4.6` is dependent on `appium-adb v1.7.5`, this leads to the failure of automation. I can send you the PR for 1.7.5 if you confirm this is a valid bug.

**Comment by imurchie** [comment]
Can you upgrade to Appium 1.5 and try again? Further work on dependencies of 1.4 are not going to be done.

**Comment by imurchie** [comment]
Any changes on upgrade? I don't think that it is currently a feature to allow multiple wait packages/activities. It could be added at some point, though.

**Comment by email2vimalraj** [comment]
Yes, I don't see Appium 1.5 support Multiple activities. I would suggest we should support this in 1.5. I'll see if I can send a PR for this.

**Comment by imurchie** [comment]
That would be awesome! Otherwise we can add it to our list of things to do.

**Comment by rkavalap** [comment]
Issue moved to [appium/appium #7390](https://github.com/appium/appium/issues/7390) via [**ZenHub**](https://www.zenhub.com/)
