### ISSUE TITLE
APK install timeout is hardcoded

### ISSUE THREAD

**Issue by sylvinus** [appium/appium-adb#147]
Hi,

Despite setting --launch-timeout to a very high value, I kept having a timeout of 60000ms. I have to change it directly in the code to fix it:
https://github.com/appium/appium-adb/blob/806f31e727d5b07458a62f5693a16d68f9fe6597/lib/tools/apk-utils.js#L171

I'm not sure the issue is in `appium-adb` itself, but it seems that the command-line timeout parameters have not much influence on the actual timeouts.

thanks!

**Comment by t-d-d** [comment]
Also a hardcode 90000ms here https://github.com/appium/appium-android-driver/blob/9dd4816528576ad5bc45f3cfaab1c580cf7e8235/lib/android-helpers.js#L243

Should these values take account of ADB_INSTALL_TIMEOUT ?

I'm using a fork with these values increased https://github.com/t-d-d/appium which seems to solve my issues.  I can do a PR if we agree the best approach.

**Comment by imurchie** [comment]
`--launch-timeout` is an iOS-only server argument. See https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md

There is currently no way to change the install timeout. We'd be open to PRs to fix this, though!

**Comment by spearminty** [comment]
Please have a look at appium-android-driver 1.10.12 and the respective merge into appium master

The addition of a capability to change the install timeout should resolve this issue: androidInstallTimeout

**Comment by rkavalap** [comment]
Closing this as it's already fixed
