### ISSUE TITLE
Can no longer connect to Android Emulator with Android SDK Tools 25.1.1

### ISSUE THREAD

**Issue by garyjohnson** [appium/appium-adb#150]
Just got appium up and running yesterday on an Android project. Updated the tools this morning (and nothing else), then noticed that appium started raising errors when attempting to talk to the android emulator.

Behavior: When appium driver is started, the configured AVD emulator will start, but then appium will fail to communicate with it and raise an exception. On a second run, it will fail to see the running emulator and start another instance, then fail again for the same issue.

Full appium log: https://gist.github.com/garyjohnson/7690fa79a1aeb1ee9f26cbb5082d8868

Details: appium-adb appears to fail specifically when running `avd name` over telnet connection. One thing I noticed is that it looks like there is loopback data on the telnet connection (i.e., you can see "avd name" returned in the telnet data along with the emulator name), but unsure if this is how it behaved previously:

```
[debug] [ADB] Sending telnet command to device: avd name
[debug] [ADB] Getting running emulator port
[debug] [ADB] Socket connection to device created
[debug] [ADB] Socket connection to device ready
[debug] [ADB] Telnet command got response: a[K[Dav[K[D[Davd[K[D[D[Davd [K[D[D[D[Davd n[K[D[D[D[D[Davd na[K[D[D[D[D[D[Davd nam[K[D[D[D[D[D[D[Davd name[K
Testing
[debug] [ADB] Emulator Testing not running
```

Running Appium 1.5.1, NPM 3.3.12, OSX El Capitan 10.11.4, Node 5.4.0, Android SDK Tools 25.1.1, Android SDK Build-Tools 23.0.2

**Comment by garyjohnson** [comment]
Wanted to follow up on this -- I did a test of stripping the first line from the telnet response in [lib/tools/adb-commands.js](lib/tools/adb-commands.js):

```
232         if (readyRegex.test(data)) {
233           res = dataStream.replace(readyRegex, "").trim();
234           var newlineIndex = res.indexOf("\n");
235           res = res.substr(newlineIndex + 1);
236           log.debug(`Telnet command got response: ${res}`);
237           conn.write("quit\n");
```

This did fix the issue and allow me to connect to AVD. I don't have enough context around this to know 1) if this will break some other telnet command routing through adb-commands, 2) how to handle this for people who have not upgraded, 3) why this happens in the first place.

Ideally this behavior could just be disabled somehow? Stripping the first line unconditionally is a total hack.

I'm going to try to roll back to a previous version of the SDK tools and verify that it starts working again, just to rule out the idea of some other environmental change causing this issue (and as a workaround).

**Comment by imurchie** [comment]
Interesting. Thanks for the report!

The quick answer to (3) is that Android changes things at its own whim.

I will look into the other changes and try to find a way that supports old and new.

**Comment by imurchie** [comment]
I'm having a problem getting the latest SDK tools. Could you try something for me?

Replace the code in the connected block (where you made the change before) with:

```js
res = dataStream.replace(readyRegex, "").trim();
res = _.last(res.split('\n'));
log.debug(`Telnet command got response: ${res}`);
conn.write("quit\n");
```

**Comment by imurchie** [comment]
Sorry, the added line needs to be `res = _.last(res.trim().split('\n'));` in order to not fail if there is a newline at the end.

**Comment by garyjohnson** [comment]
Appears to work well (testing by directly calling getRunningAVD). I'll patch it in locally and make sure everything works okay.

**Comment by dduphorn** [comment]
I'm running into the same issue.   How can I get this fixed?

**Comment by imurchie** [comment]
What version of appium are you running? It will _only_ work on 1.5.2 or later.

**Comment by dduphorn** [comment]
Thanks for getting back to me so quickly.

I’m on Version 1.5.2 (Ara)

Darin

On May 4, 2016, at 1:17 PM, Isaac A. Murchie <notifications@github.com<mailto:notifications@github.com>> wrote:


What version of appium are you running? It will only work on 1.5.2 or later.

**Comment by imurchie** [comment]
Can you provide a [gist](https://gist.github.com/) of the full Appium server logs, then?

**Comment by dduphorn** [comment]
My bad, it actually did fix the issue when I used the Launch button from Appium.  It failed when I start appium server programmatically. Using the below code.

public void startServer()
{
		CommandLine command = new CommandLine("/Applications/               Appium.app/Contents/Resources/node/bin/node");
		//OLD command.addArgument("/Applications/Appium.app/Contents/Resources/node_modules/appium/bin/appium.js",false);
		command.addArgument("/Users/darinduphorn/node_modules/appium/bin/appium.js",false);
		command.addArgument("--address", false);
		command.addArgument("127.0.0.1");
		command.addArgument("--port", false);
		command.addArgument("4723");
		//command.addArgument("--full-reset", false);
		//command.addArgument("--no-reset", true);
		DefaultExecuteResultHandler resultHandler = new DefaultExecuteResultHandler();
		DefaultExecutor executor = new DefaultExecutor();
		executor.setExitValue(1);
		try {executor.execute(command, resultHandler);Thread.sleep(5000);System.out.println("Appium server started.");}
		catch (IOException e) {e.printStackTrace();}
		catch (InterruptedException e) 
		{e.printStackTrace();}
}

**Comment by imurchie** [comment]
That is an entirely different issue. Please file an issue with it (probably on the Java client).

**Comment by dduphorn** [comment]
Ok, I am getting the same telnet error: Telnet command got response: a[K[Dav[K[D[Davd[K[D[D[Davd [K[D[D[D[Davd n[K[D[D[D[D[Davd na[K[D[D[D[D[D[Davd nam[K[D[D[D[D[D[D[Davd name[K.. I guess I could include this thread in the issue.

**Comment by imurchie** [comment]
We need the entire logs. As a gist.

**Comment by dduphorn** [comment]
Did I create this correctly?

https://gist.github.com/dduphorn/993f6ee5f159e21762bef763b431c02d

**Comment by imurchie** [comment]
Yes. But this is for version 1.4.16. There is no chance of it ever working. The fix is in 1.5.2.

**Comment by dduphorn** [comment]
Ah, I see what you are saying.  I when I upgraded Appium it removed the below file.
/Applications/Appium.app/Contents/Resources/node_modules/appium/bin/appium.js

I searched my machine for appium.js, and it found it here.
/Users/darinduphorn/node_modules/appium/bin/appium.js

Where that is probable the 1.4.16 version.  

Any idea where appium would have put the new appium.js?  

Thanks

**Comment by imurchie** [comment]
It doesn't exist anymore. 1.5 runs from `build/lib/main.js`. You can download a beta of the app for 1.5.2 from https://bitbucket.org/appium/appium.app/downloads

**Comment by dduphorn** [comment]
Sorry for my confusion, but where is build/lib/main.js?  Is that what I need to download?  

When I open that link I don't see any thing call main.js.

**Comment by imurchie** [comment]
You are running in the downloaded app, correct? With the GUI on Mac? The 1.5.2 version of the app will have it inside, no need to change anything.

**Comment by dduphorn** [comment]
I got it working when I run from the GUI on Mac.  I'm trying to programmatically start the appium server.  I've updated my Arguments to include build/lib/main.js.

CommandLine command = new CommandLine("/Applications/Appium.app/Contents/Resources/node/bin/node");
		command.addArgument("build/lib/main.js",false);
		command.addArgument("--address", false);
		command.addArgument("127.0.0.1");
		command.addArgument("--port", false);
		command.addArgument("4723");

The error I get is: 

module.js:341
    throw err;
    ^

Error: Cannot find module '/Users/darinduphorn/git/TestAutomation/TestAutomation/build/lib/main.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
    at node.js:404:3

So I'm wondering where build/lib/main.js is located so I can start Appium server programmatically.

Thanks

**Comment by imurchie** [comment]
If you don't care about the GUI, just install appium locally from npm.

In your current directory, run `npm install appium` and it should create a directory `node_modules` inside of which will be a directory `appium`. The runnable file is in there.

**Comment by dduphorn** [comment]
I got it to work.  Thanks for your help.

CommandLine command = new CommandLine("/Applications/Appium.app/Contents/Resources/node/bin/node");
command.addArgument("/Users/darinduphorn/node_modules/appium/build/lib/main.js",false);
command.addArgument("--address", false);
command.addArgument("127.0.0.1");
command.addArgument("--port", false);
command.addArgument("4723");

**Comment by HarshavardhanShastry** [comment]
Getting the same error can any one help me out.Presently i have 1.4.13.1, but showing latest update to update is 1.4.16.1.how can i solve this. Stuck with not able to run the app itsels.
![screenshot 29](https://cloud.githubusercontent.com/assets/22667427/19167428/4fc4fe54-8c29-11e6-9329-b108c9905e36.png)
