### ISSUE TITLE
Parsing of "intentOptionalArgs" with a value contening ' - '

### ISSUE THREAD

**Issue by Fanch-** [appium/appium-adb#161]
Hello, with `-` character in optional intent args it might have a parsing problem : 

```shell```
[HTTP] --> POST /wd/hub/session/618433d1-fd70-4ad6-bfc2-75294d8e684d/appium/device/start_activity {"appPackage":"android","appActivity":"com.android.internal.app.ResolverActivity","appWaitPackage":"","appWaitActivity":"","dontStopAppOnReset".intent.action.VIEW","intentCategory":"android.intent.category.BROWSABLE","intentFlags":"","optionalIntentArguments":"-d 'https://www2.qa0.bon-coin.net/vi/1070547.htm'"}
```

Then :

```shell```
[debug] [ADB] Running /home/fanch/Downloads/android-sdk-linux/platform-tools/adb with args: ["-P",5037,"-s","ENU7N15B14002933","shell","am","start","-n","android/com.android.internal.app.ResolverActivity","-S","-a","android.intent.action.VIE {...} ry.BROWSABLE","-d","'https://www2.qa0.bon"]
```

We can see the url stops at the `-`.

adb equivalent working : 
```shell```
adb -s $1 shell "am start -a android.intent.action.VIEW -c android.intent.category.BROWSABLE -d https://www2.qa0.bon-coin.net/vi/1070547.htm"
```
I guess there is a check with the `-` character for other optional intent arguments, need to ignore it in values (Same using 'url' or url, it isn't a quote issue). 

By the way appActivity and appPackage are not necessary to open a deep link, what about add a 

> startIntent(String intentAction,String intentCategory,
> String intentFlags,String intentOptionalArgs)

method in java-client?

**Comment by imurchie** [comment]
Thank you for the update. I've opened a PR to fix the hyphen problem.
