### ISSUE TITLE
The apk is not being installed with "-gr" key

### ISSUE THREAD

**Issue by sergey-plevako-badoo** [appium/appium-adb#175]
The "-g" for the apkUtilsMethods.installFromDevicePath does not work for me.
The apk is not being installed from the /tpm folder. 
This affects appium-adb 2.6.14
apk-utils.js:173

> let stdout = await this.shell(['pm', 'install', '-gr', apkPathOnDevice], opts);

It works fine is the previous release (2.6.13) which has "-r" key only
My ADB version is: 
`
Plevakos-829:appium-adb sergeyplevako$ adb version
Android Debug Bridge version 1.0.36
Revision af05c7354fe1-android
`

**Comment by imurchie** [comment]
Can you be more specific about 'does not work for me'?

**Comment by sergey-plevako-badoo** [comment]
The following command (which appium-adb uses) does not work for me
`Plevakos-829:appium-adb sergeyplevako$ adb shell pm install -gr /tmp/fffc85c0df0a906bef57bb376a718b71.apk
Error: Unknown option: -g`

**Comment by imurchie** [comment]
Ok. I'm removing it. It's been more trouble than it is worth.

**Comment by sergey-plevako-badoo** [comment]
However, the 
`adb shell pm install -rg /tmp/fffc85c0df0a906bef57bb376a718b71.apk` 
works fine

**Comment by imurchie** [comment]
Ha! But apparently it does not do what the `g` is supposed to do, when in that order. Alas.

**Comment by rkavalap** [comment]
Issue moved to [appium/appium #7392](https://github.com/appium/appium/issues/7392) via [**ZenHub**](https://www.zenhub.com/)
