### ISSUE TITLE
Still not working on Nougat

### ISSUE THREAD

**Issue by Mygod** [appium/appium-adb#177]
I'm using 2.6.16 and is still getting this error:

```
[UiAutomator] Error while killing uiAutomator: Error: Unable to kill uiautomator processes. Original error: Unable to get pids for uiautomator. Orginial error: Could not extract PID from ps output: bad pid 'uiautomator'
```

Which is still caused by here: https://github.com/appium/appium-adb/blob/master/lib/tools/adb-commands.js#L429

After fixing this myself (removing `, name`), it works fine again.

**Comment by imurchie** [comment]
Can you provide more information so that we can test this out?

**Comment by Mygod** [comment]
I run this on Nougat: https://github.com/Mygod/chimpanzeerunner
