### ISSUE TITLE
Testing system apps

### ISSUE THREAD

**Issue by rickybscs** [appium/appium-adb#183]
Hi there, I have a situation where our app installs as a system app.  Appium tries to do a pm list with -3 parameter which never returns our package.  It would need to use -s

In any case, the issue is that Appium is not able to launch our activity.  If I run the exact same shell am start command from the command line it works fine.

Are there any special flags I need to use to get appium to automate system apps?

**Comment by rkavalap** [comment]
Issue moved to [appium/appium #7393](https://github.com/appium/appium/issues/7393) via [**ZenHub**](https://www.zenhub.com/)
