### ISSUE TITLE
targetSdkVersionFromManifest fails if apk does not include targetSdkVersion

### ISSUE THREAD

**Issue by john7doe** [appium/appium-adb#188]
Steps to reproduce:

copy settings_apk-debug.apk from io.appium.settings to test/fixtures/settings_apk-debug.apk

change the following in android-manifest-e2e-specs.js:
```
-                                'selendroid', 'selendroid.apk');
+                                'selendroid', 'selendroid.apk'),
+      settingsApp = path.resolve(rootDir, 'test', 'fixtures', 'settings_apk-debug.apk');
```

add this to the 'Android-manifest' spec:

 it('targetSdkVersionFromManifest works on our own settingsApp', async () => {
    let version = adb.targetSdkVersionFromManifest(settingsApp);
});

**Comment by john7doe** [comment]
It could be that this behaviour is intended, but in that case then the use in apk-utils.js need to take this into account in its install method

**Comment by john7doe** [comment]
related to https://github.com/appium/appium/issues/7349

**Comment by rkavalap** [comment]
Issue moved to [appium/appium #7394](https://github.com/appium/appium/issues/7394) via [**ZenHub**](https://www.zenhub.com/)
