### ISSUE TITLE
Allow custom sigalg, digestalg

### ISSUE THREAD

**Issue by bootstraponline** [appium/appium-adb#32]
Custom sigalg / digestalg has been requested on the mailing list.

https://github.com/appium/appium-adb/blob/af9fd45a94dd1cd058a6008e07d5783ec834aedf/lib/adb.js#L401

**Comment by rkavalap** [comment]
Issue moved to [appium/appium #7384](https://github.com/appium/appium/issues/7384) via [**ZenHub**](https://www.zenhub.com/)
