### ISSUE TITLE
Can it add display option to startApp ?

### ISSUE THREAD

**Issue by chaooe** [appium/appium-adb#514]
**Warning:**

These issues are not tracked. Please create new issues in the main Appium
repository: https://github.com/appium/appium/issues/new
Our android device have two more display which we can launch on different display. commands looks like below:
`adb -P 5037 -s 10.13.100.18\:5555 shell am start -W -n pkg/.act -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 --display 1`
So we can use this parameter on appium-uiautomator2 to start on another display.

**Comment by chaooe** [comment]
@mykola-mokhnach This feature is the same as https://github.com/appium/appium-espresso-driver/pull/557 I think it is useful for my current devices.

**Comment by mykola-mokhnach** [comment]
You could try `optionalIntentArguments` cap. Btw, we don't track issues of this repository and this is clearly stated in the warning above

**Comment by chaooe** [comment]
You are right, I tried it. it works to use `optionalIntentArguments="--display 1"` 
thanks
