### ISSUE TITLE
README.md:「import ADB from 'appium-adb'」should be「import {ADB} from 'appium-adb'」

### ISSUE THREAD

**Issue by mitsukuri** [appium/appium-adb#649]
Getting `ADB.createADB is not a function` error otherwise.

**Comment by jlipps** [comment]
@mitsukuri want to make a PR to fix?

**Comment by mykola-mokhnach** [comment]
Is this an issue for ESM modules? I can observe that index.js does contain `export default ADB;`. @boneskull is an expert in such things

**Comment by mitsukuri** [comment]
> @mitsukuri want to make a PR to fix?

No problem, just wanted to make sure this is a bug, not feature :)

**Comment by jlipps** [comment]
@mitsukuri can you say more about why `import ADB` didn't work for you?

**Comment by mitsukuri** [comment]
```
import ADB from 'appium-adb';
const adb = await ADB.createADB ();
```
results in
```
TypeError: ADB.createADB is not a function
    at file:///mnt/ntfs/d/code/projects/test/hands/src/adb.mjs:13:23
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at loadESM (node:internal/process/esm_loader:91:5)
    at handleMainPromise (node:internal/modules/run_main:65:12)
```
while `import ADB from 'appium-adb'` does not
